#!/usr/bin/env python3
"""Generate conceptual Chapter 9 rule-circuit figures.

These figures are schematic. They illustrate hypotheses and evidence boundaries;
measured plots are generated by the dedicated MLP7 Chapter 9 scripts.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIG = ROOT / "docs" / "figures"

STYLE = """<style>
svg{color-scheme:light dark;--text:#172033;--muted:#5c667a;--grid:#d8dde8;--fill:#f7f9fc;--target:#f2c94c;--opp:#cc4b37;--mine:#246bfe;--empty:#b8c0d0;--teal:#0f8f7f;--weak:#9aa3b7}
@media(prefers-color-scheme:dark){svg{--text:#eef2ff;--muted:#b7bfd1;--grid:#384153;--fill:#1f2633;--target:#ffd766;--opp:#ff8f7d;--mine:#86a9ff;--empty:#5a6578;--teal:#5fd4c7;--weak:#808ba0}}
.title{font:700 24px system-ui,-apple-system,Segoe UI,sans-serif;fill:var(--text)}.label{font:600 13px system-ui,-apple-system,Segoe UI,sans-serif;fill:var(--text)}.small{font:12px system-ui,-apple-system,Segoe UI,sans-serif;fill:var(--muted)}
.box{fill:var(--fill);stroke:var(--grid);stroke-width:1.3;rx:8}.line{stroke:var(--grid);stroke-width:2;fill:none;marker-end:url(#arrow)}.teal{stroke:var(--teal);stroke-width:3;fill:none;marker-end:url(#arrowTeal)}.weak{stroke:var(--weak);stroke-width:2;stroke-dasharray:6 5;fill:none;marker-end:url(#arrowWeak)}
.target{fill:var(--target);stroke:var(--grid);stroke-width:1.2}.opp{fill:var(--opp);stroke:var(--grid);stroke-width:1.2}.mine{fill:var(--mine);stroke:var(--grid);stroke-width:1.2}.empty{fill:var(--empty);stroke:var(--grid);stroke-width:1.2}.frontier{stroke:var(--opp);stroke-width:2.4;stroke-dasharray:7 5}
</style>
<defs>
<marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L0,6 L9,3 z" fill="#5c667a"/></marker>
<marker id="arrowTeal" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L0,6 L9,3 z" fill="#0f8f7f"/></marker>
<marker id="arrowWeak" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L0,6 L9,3 z" fill="#9aa3b7"/></marker>
</defs>"""


def write(name: str, body: str) -> None:
    (FIG / name).write_text(body, encoding="utf-8")


def relational_capture_conditions() -> None:
    conditions = [
        ("valid capture", ["target", "opp", "opp", "mine"], "legal ray"),
        ("no terminator", ["target", "opp", "opp", "empty"], "invalid"),
        ("friendly adjacent", ["target", "mine"], "invalid"),
        ("empty adjacent", ["target", "empty"], "invalid"),
        ("broken line", ["target", "opp", "empty", "mine"], "invalid control"),
    ]
    rows = []
    for i, (name, pieces, note) in enumerate(conditions):
        y = 120 + i * 72
        rows.append(f'<text class="label" x="64" y="{y+19}">{name}</text>')
        for j, piece in enumerate(pieces):
            x = 230 + j * 78
            rows.append(f'<circle class="{piece}" cx="{x}" cy="{y}" r="19"/>')
            label = {"target": "T", "opp": "O", "mine": "M", "empty": "E"}[piece]
            rows.append(f'<text class="label" x="{x}" y="{y+5}" text-anchor="middle">{label}</text>')
            if j < len(pieces) - 1:
                rows.append(f'<line class="line" x1="{x+24}" y1="{y}" x2="{x+54}" y2="{y}"/>')
        rows.append(f'<text class="small" x="600" y="{y+5}">{note}</text>')
    body = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 820 520" role="img" aria-labelledby="title desc">
<title id="title">Relational capture conditions</title>
<desc id="desc">Matched structural ray conditions for testing candidate MLP7 neurons.</desc>
{STYLE}
<text class="title" x="42" y="48">Relational capture conditions</text>
<text class="small" x="42" y="72">Matched structural conditions used to ask whether MLP7 neurons distinguish the relational ingredients of Othello legality.</text>
{''.join(rows)}
<circle class="target" cx="94" cy="476" r="9"/><text class="small" x="110" y="480">target</text>
<circle class="opp" cx="174" cy="476" r="9"/><text class="small" x="190" y="480">opponent</text>
<circle class="mine" cx="272" cy="476" r="9"/><text class="small" x="288" y="480">friendly</text>
<circle class="empty" cx="358" cy="476" r="9"/><text class="small" x="374" y="480">empty</text>
</svg>
'''
    write("relational_capture_conditions.svg", body)


def detector_vs_writer() -> None:
    body = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 820 450" role="img" aria-labelledby="title desc">
<title id="title">Detector versus writer evidence</title>
<desc id="desc">A neuron input side and output side can have different interpretability evidence.</desc>
{STYLE}
<text class="title" x="42" y="48">A neuron has an input side and an output side</text>
<text class="small" x="42" y="72">Neuron 399 is more interpretable from output geometry than from valid-capture activation selectivity.</text>
<rect class="box" x="72" y="140" width="185" height="80"/><text class="label" x="164" y="172" text-anchor="middle">residual features</text><text class="small" x="164" y="196" text-anchor="middle">mixed board / context state</text>
<path class="weak" d="M257 180 L340 180"/><text class="small" x="280" y="164">W_in</text>
<rect class="box" x="340" y="140" width="140" height="80"/><text class="label" x="410" y="172" text-anchor="middle">activation</text><text class="small" x="410" y="196" text-anchor="middle">post-GELU scalar</text>
<path class="teal" d="M480 180 L565 180"/><text class="small" x="507" y="164">W_out</text>
<rect class="box" x="565" y="140" width="190" height="80"/><text class="label" x="660" y="172" text-anchor="middle">residual write</text><text class="small" x="660" y="196" text-anchor="middle">legality-gradient aligned</text>
<rect class="box" x="72" y="278" width="310" height="86"/><text class="label" x="227" y="307" text-anchor="middle">input-side evidence</text><text class="small" x="227" y="331" text-anchor="middle">valid-vs-invalid selectivity for neuron 399: -0.125210</text><text class="small" x="227" y="352" text-anchor="middle">not a clean valid-capture detector in this test</text>
<rect class="box" x="445" y="278" width="310" height="86"/><text class="label" x="600" y="307" text-anchor="middle">output-side evidence</text><text class="small" x="600" y="331" text-anchor="middle">mean post activation: 0.604659</text><text class="small" x="600" y="352" text-anchor="middle">activation x legality write: -0.076923</text>
</svg>
'''
    write("neuron_detector_vs_writer.svg", body)


def distributed_hypothesis() -> None:
    neurons = []
    for i in range(9):
        x = 340 + (i % 3) * 68
        y = 138 + (i // 3) * 56
        neurons.append(f'<circle class="box" cx="{x}" cy="{y}" r="22"/><text class="small" x="{x}" y="{y+4}" text-anchor="middle">n</text>')
    body = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 820 430" role="img" aria-labelledby="title desc">
<title id="title">Distributed MLP7 hypothesis</title>
<desc id="desc">Current mechanistic hypothesis where several MLP7 neurons jointly contribute to a legality-relevant write.</desc>
{STYLE}
<text class="title" x="42" y="48">Current hypothesis: a distributed MLP7 population</text>
<text class="small" x="42" y="72">Current mechanistic hypothesis -- not an established complete circuit.</text>
<rect class="box" x="64" y="156" width="190" height="96"/><text class="label" x="159" y="188" text-anchor="middle">mixed residual features</text><text class="small" x="159" y="213" text-anchor="middle">board state, move context,</text><text class="small" x="159" y="233" text-anchor="middle">attention-routed information</text>
<path class="teal" d="M254 204 L310 204"/>
{''.join(neurons)}
<path class="teal" d="M540 204 L604 204"/>
<rect class="box" x="604" y="156" width="170" height="96"/><text class="label" x="689" y="188" text-anchor="middle">population write</text><text class="small" x="689" y="213" text-anchor="middle">legality-relevant</text><text class="small" x="689" y="233" text-anchor="middle">residual update</text>
<text class="small" x="334" y="304">Individual neurons can be selective, writer-like, polysemantic, or mostly silent in a given context.</text>
</svg>
'''
    write("distributed_mlp7_hypothesis.svg", body)


def evidence_ladder_rule_circuit() -> None:
    steps = [
        ("Behavior", "established"),
        ("Board representation", "strong"),
        ("Semantic causality", "strong"),
        ("Layer-7 localization", "strong"),
        ("MLP7 localization", "strong"),
        ("candidate neuron population", "mixed / partial"),
        ("output-write geometry", "moderate"),
        ("small selected-neuron causality", "weak positive"),
        ("relational detector", "open"),
        ("path mediation", "open"),
        ("rescue / sufficiency", "open"),
        ("complete algorithmic circuit", "not established"),
    ]
    rows = []
    for i, (label, note) in enumerate(steps):
        y = 76 + i * 36
        rows.append(f'<rect class="box" x="230" y="{y}" width="330" height="26"/><text class="label" x="395" y="{y+18}" text-anchor="middle">{label}</text><text class="small" x="580" y="{y+18}">{note}</text>')
        if i < len(steps) - 1:
            rows.append(f'<path class="line" d="M395 {y+26} L395 {y+36}"/>')
    body = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 840 560" role="img" aria-labelledby="title desc">
<title id="title">Evidence ladder for rule circuits</title>
<desc id="desc">Evidence frontier for Chapter 9 rule-circuit hunting.</desc>
{STYLE}
<text class="title" x="42" y="44">Evidence frontier after hunting rule circuits</text>
{''.join(rows)}
<line class="frontier" x1="190" y1="253" x2="722" y2="253"/><text class="small" x="42" y="257">strong evidence frontier</text>
<line class="frontier" x1="190" y1="361" x2="722" y2="361"/><text class="small" x="42" y="365">mixed neuron frontier</text>
</svg>
'''
    write("evidence_ladder_rule_circuit.svg", body)


def main() -> None:
    FIG.mkdir(parents=True, exist_ok=True)
    relational_capture_conditions()
    detector_vs_writer()
    distributed_hypothesis()
    evidence_ladder_rule_circuit()


if __name__ == "__main__":
    main()
